Laba_monolit/za_monolit-master/mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mysite import settings
# import sys
# sys.path.append("..")
from polls import views

urlpatterns = [
    path('', views.homeView, name='home'),
    path('polls/', include('polls.urls') ),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Laba_monolit/za_monolit-master/mysite/polls/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.conf.urls.static import static

from mysite import settings
from . import views

app_name = 'polls'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('registration/', views.regView, name='reg'),
    path('registration/login', views.MyLoginView.as_view(), name='login'),
    path('accounts/<int:pk>', views.Profile.as_view(), name='profile'),
    path('delete_profile/<int:pk>', views.delete_profile, name='del_prof'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('historylist/', views.HistoryList.as_view(), name='history'),
]

Laba_monolit/za_monolit-master/mysite/polls/models.py
import datetime

from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name = models.CharField(max_length=100, verbose_name="Имя", blank=True)
    surname = models.CharField(max_length=100, verbose_name="Фамилия", blank=True)
    username = models.CharField(max_length=100, verbose_name="Логин", unique=True)
    mail = models.EmailField(verbose_name="Ваша почта", unique=True)
    password = models.CharField(max_length=100, verbose_name="Пароль")
    password2 = models.CharField(max_length=100, verbose_name="Повторите пароль")
    avatar = models.ImageField(verbose_name="Загрузите аватарку", upload_to='avatars')


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    main_text = models.TextField(blank=True, default=" ", null=True)
    img = models.ImageField(upload_to='img_for_questions', null=True, blank=True, default=None)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class VotedUsers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

Laba_monolit/za_monolit-master/mysite/polls/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from .models import *


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'surname', 'username', 'mail', 'password', 'password2', 'avatar']
        widgets = {
            'password': forms.PasswordInput(attrs={'name': 'password', 'type': 'password', 'autocomplete': 'off'}),
            'password2': forms.PasswordInput(attrs={'name': 'password2', 'type': 'password', 'autocomplete': 'off'}),
        }


class MyAuthenticationForm(forms.ModelForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'password':forms.PasswordInput(attrs={}),
        }

class ProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['name', 'surname', 'mail', 'password', 'avatar']

Laba_monolit/za_monolit-master/mysite/polls/views.py
from django.contrib.auth import login

from django.contrib.auth.views import LoginView
from django.db.models import Sum, F, FloatField
from django.db.models.functions import Cast
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, UpdateView, DeleteView, RedirectView

from .models import Question, Choice, User, VotedUsers
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic
from .forms import RegistrationForm, MyAuthenticationForm, ProfileForm


def homeView(request):
    return render(request, 'home.html')

def regView(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            if form.cleaned_data['password'] == form.cleaned_data['password2']:
                new_user = form.save(commit=False)
                new_user.set_password(form.cleaned_data['password'])
                new_user.password2 = 'NULL'
                new_user = form.save()
                login(request, new_user)
                # return render(request, 'polls/reg_success.html')
                return redirect('polls:login')
        else:
            return render(request, 'polls/registration.html', {'form': form})

    else:
        form = RegistrationForm()
        return render(request, 'polls/registration.html', {'form':form})

class MyLoginView(LoginView):
    template_name = 'polls/login.html'
    form = MyAuthenticationForm
    next_page = 'polls:index'

    # def get_success_url(self):
    #     return reverse_lazy('polls:index')





class Profile(UpdateView):
    model = User
    fields = ['name', 'surname', 'mail', 'avatar']
    success_url = reverse_lazy('polls:index')
    template_name = 'polls/accounts/profile.html'

def delete_profile(request, pk):
    obj = User.objects.get(pk=pk)
    obj.delete()
    return render(request, 'polls/delete_success.html')





class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def dispatch(self, request, *args, **kwargs):
        question = get_object_or_404(Question, pk=kwargs['pk'])
        if VotedUsers.objects.filter(user=request.user, question=question.pk).exists():
            var=int(kwargs['pk'])
           # return RedirectView.as_view(url='polls:results')(request, *args, **kwargs) 3
            return redirect(reverse('polls:results', args= (var,)))

        stub = Question.objects.get(pk=kwargs['pk'])
        if stub.was_published_recently():
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect(reverse_lazy('polls:index'))


#def result_view(request, *args):
#    key = args[0]
#    question = Question.objects.get(pk=key)
#    return render(request, 'polls/results.html', context={'question': question })


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = Question.objects.get(pk=self.kwargs['pk'])
        #total_votes = q.choice_set.aggregate(total_votes=Sum('votes'))['total_votes']
        total_votes = q.choice_set.aggregate(total_votes=Sum(Cast('votes', FloatField())))['total_votes']
        choices_with_percent = (q.choice_set.annotate(percent=(F('votes') / total_votes) * 100)
                                .values('choice_text', 'percent'))
        context['question'] = q
        context['total_votes'] = total_votes
        context['choices_with_percents'] = choices_with_percent
        return context





def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'вы не сделали выбор'
        })
    else:
        if VotedUsers.objects.filter(user=request.user, question=question.pk).exists():
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        else:
            VotedUsers.objects.create(user=request.user, question= question)
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class HistoryList(generic.ListView):
    model= Question
    template_name = 'polls/historylist.html'
    context_object_name = 'lst'

Laba_monolit/za_monolit-master/mysite/polls/templates/polls/delete_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>:)</title>
</head>
<body>
    <h2>Удаление вашего профиля прошло успешно</h2>
    <br>
    <a href="{% url 'home' %}">Перейти на главную страницу</a>
</body>
</html>

Laba_monolit/za_monolit-master/mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% if question.main_text %}
            <h4>{{ question.main_text }}</h4>
    {% endif %}
    {% if question.img %}
        <img src="{{ question.img.url }}" alt="some_image" style="width:200px;">
    {% endif %}
    <fieldset>
        <legend>
            <h1>{{question.question_text}}</h1>
        </legend>
        {% if error_message %}<p><strong> {{error_message}}</strong></p>{% endif %}

        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
    </fieldset>
<input type="submit" value="Vote">
</form>

Laba_monolit/za_monolit-master/mysite/polls/templates/polls/historylist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>История опросов</title>
</head>
<body>
<h2>Список всех опросов которые были проведены или проводятся.</h2>
<a href="{% url 'polls:index' %}"><h4>Вернуться на главную</h4></a><br><br>
    {% for i in lst %}
        <div><a href="{% url 'polls:results' i.pk %}">{{ i.question_text }}</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Опубликовано: {{ i.pub_date }}</div>
    {% endfor %}
</body>
</html>

Laba_monolit/za_monolit-master/mysite/polls/templates/polls/index.html
{% if user.avatar %}
    <img src="{{ user.avatar.url }}" alt="avatarka" style="width: 50px;"><h3>{{ user.username }} </h3>
{% endif %}

{% if latest_question_list %}
{% if user.is_superuser %}
    <h3>Здравствуйте {{ user.username|upper}}</h3>
{% else %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a> </li>
        {% endfor %}
    </ul>
{% endif %}
    {% if user.is_superuser %}
        <a href="{% url 'polls:profile' user.pk  %}">Личный кабинет</a><br>
        <a href="{% url 'polls:history'  %}">Просмотр истории опросов</a><br>
        <a href="{% url 'polls:logout'  %}">Выйти</a>
    {% elif user.is_authenticated %}
        <a href="{% url 'polls:profile' user.pk  %}">Личный кабинет</a><br>
        <a href="{% url 'polls:logout'  %}">Выйти</a>
    {% endif %}
    {% else %}
     <p>
         Нет вопросов!
     </p>

{% endif %}

Laba_monolit/za_monolit-master/mysite/polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post" action="" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Отправить данные </button>
    </form>
</body>
</html>

Laba_monolit/za_monolit-master/mysite/polls/templates/polls/reg_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вы зарегистриваны</title>
</head>
<body>
    <h2>Вы зарегистрированы</h2>
</body>
</html>

Laba_monolit/za_monolit-master/mysite/polls/templates/polls/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация пользователя</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" >Зарегестрироваться</button>
    </form>
</body>
</html>

Laba_monolit/za_monolit-master/mysite/polls/templates/polls/results.html
{% load custom_filter %}

<h1>{{ question.question_text }}</h1>
{% if question.main_text.exists      %}
    <h4>{{ question.main_text }}</h4>
{% endif %}
{% if question.img %}
    <img src="{{ question.img.url }}" alt="some_image" style="width:200px;">
{% endif %}

{% if choices_with_percents %}
    <ul>
        {% for choice in choices_with_percents %}
            <li>{{ choice.choice_text }} -- {{ choice.percent|default:0|trunc }}% vote{{choice.votes|pluralize}}</li>
        {% endfor %}
    </ul>
{% endif %}
<p>ВСЕГО ГОЛОСОВАЛО: <b>{{ total_votes|trunc }}</b></p>
{% if user.is_superuser %}
    <a href="{% url 'polls:history' %}">Вернуться</a>
{% else %}
    <a href="{% url 'polls:detail'  question.id %}">Выбрать еще раз? </a><br>
    <a href="{% url 'polls:index' %}">Вернуться</a>
{% endif %}
<br>